test: &default

  # Credentials for REST APIs
  client_id: AV1n4FJooNUj-xW_gF5U-sgBFGSnToY-SMpv43Rcd0DdEKe_5giMEh9zzVrYVbHxM5XWB6pDfYy4uBs_
  
  # Sandbox Secret
  client_secret: EJkQjn_jPXxFHXOzWCVmIvLT1tKmeJmVtm1Bwm-WYStvxY9HNlKhnyqlpxEWMDmZgqvQfbnc-u8I3dhj

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs


  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
